### ISSUE TITLE
[Feature request] env-vars

### ISSUE THREAD

**Issue by l15k4** [oliver006/drone-gcf#1]
Hi, I'd like to provide PR directly but I'm a total golang newbie so I probably won't succeed. It would be nice to have support for Function's environment variables though, are you planning on doing that?

**Comment by oliver006** [comment]
Environment variables are definitely on the list of things that are still needed, it's on the near-term to-do list but no guarantees when it'll be done.
If you want to take this as an opportunity to try writing some Go then please go ahead, I'm happy to give some guidance.
