### ISSUE TITLE
How to set runtime service account?

### ISSUE THREAD

**Issue by yashbhatianyt** [oliver006/drone-gcf#26]
Hi @oliver006 ,

Thanks for providing this plugin!
I wanted to know how to set the runtime service account for a cloud function that I deployed using your plugin?

`kind: pipeline
name: default

steps:
- name: deploy-cloud-functions-dev
  image: oliver006/drone-gcf
  settings:
    action: deploy
    project: xxxxxx
    runtime: python38
    **token:
        from_secret: gcf-credentials-dev**
    functions:
      - dbt_run_http:
        - trigger: http
          memory: 512MB
          runtime: python38
          source: ./
          entry_point: dbt_run_http`

The service account for the token specified here is not the one that shows up in the Google Cloud Function UI. It routes to the default service account for runtime. Is there any way to specify here the service account it uses while running?

Thanks in advance!

**Comment by oliver006** [comment]
The token is used for the deploy, not for specifying the user that the function is run as.
I think this would need a new command line flag.

**Comment by yashbhatianyt** [comment]
<img width="734" alt="Screen Shot 2022-07-27 at 8 30 35 AM" src="https://user-images.githubusercontent.com/107452657/181247505-78dc19f6-d2ec-448b-9e8f-788134c81a37.png">

I'm looking to update the serviceAccountEmail variable as seen in this build screenshot.
When you say I would need a new command line flag, do you mean that would need some additional parameter to the drone yaml file? I can see a serviceAccount in the main.go file of your code. Does this indicate the user and is yes, how can we set it from the .drone.yml file?

<img width="679" alt="Screen Shot 2022-07-27 at 8 38 36 AM" src="https://user-images.githubusercontent.com/107452657/181248652-c36d3477-c489-483f-86e3-bc2fbac0e6be.png">

<img width="678" alt="Screen Shot 2022-07-27 at 8 38 55 AM" src="https://user-images.githubusercontent.com/107452657/181248677-57d298dc-f9d5-4bf5-ac37-aa7969e35a43.png">


Please let me know, thanks in advance!

**Comment by oliver006** [comment]
Yup, looks like you found it:
https://github.com/oliver006/drone-gcf/blob/master/main.go#L30

That adds the `--service-account` flag to the gcloud command so as long as you provide the `serviceaccount` field with the email address of your service account in your drone yaml you should be good.

**Comment by oliver006** [comment]
Closing - please re-open if you encounter the issue.
