### ISSUE TITLE
Support for --security-level=secure-always

### ISSUE THREAD

**Issue by hemarc** [oliver006/drone-gcf#31]
Hi there,
Could you by any chance add support for "--security-level=secure-always" for http trigger.

Cheers,
Marc

**Comment by oliver006** [comment]
I don't have a need for that and I'm short of time right now but I'd be happy to review and merge a PR.

**Comment by oliver006** [comment]
Closed in https://github.com/oliver006/drone-gcf/releases/tag/v1.21.0

Thanks for your PR!
